// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFEy6p9OKNbvs8_dCJZFG0i33sMAFQ7KI',
    appId: '1:1080956334233:web:4bfc8272c108a5be51c808',
    messagingSenderId: '1080956334233',
    projectId: 'scart-253c6',
    authDomain: 'scart-253c6.firebaseapp.com',
    databaseURL: 'https://scart-253c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scart-253c6.appspot.com',
    measurementId: 'G-DGL62ZZZYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnWOb2gK6OUOWhG5iXnH5ojetwWnkG_w',
    appId: '1:1080956334233:android:842812e9dfa5285151c808',
    messagingSenderId: '1080956334233',
    projectId: 'scart-253c6',
    databaseURL: 'https://scart-253c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scart-253c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAigdPOoQMzUvcN9MFO9MV2Ik6LxKm_yf4',
    appId: '1:1080956334233:ios:a185922ac172bfc051c808',
    messagingSenderId: '1080956334233',
    projectId: 'scart-253c6',
    databaseURL: 'https://scart-253c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scart-253c6.appspot.com',
    iosBundleId: 'com.example.scart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAigdPOoQMzUvcN9MFO9MV2Ik6LxKm_yf4',
    appId: '1:1080956334233:ios:5229f234db6fffda51c808',
    messagingSenderId: '1080956334233',
    projectId: 'scart-253c6',
    databaseURL: 'https://scart-253c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scart-253c6.appspot.com',
    iosBundleId: 'com.example.scart.RunnerTests',
  );
}
